kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: its-a-lisa-site-dev
  namespace: alyssa
  labels:
    app: its-a-lisa-site
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "20"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'its-a-lisa-site:dev'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: alyssa
        name: 'nodejs-20:latest'
  source:
    type: Git
    git:
      uri: 'https://github.com/its-a-lisa/its-a-lisa-site'
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: its-a-lisa-site-github
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          namespace: alyssa
          name: 'nodejs-20:latest'
    - type: ConfigChange
  runPolicy: Serial