kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: its-a-lisa-site
  namespace: alyssa
  annotations:
    cert-manager.io/cluster-issuer: le-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - its-a-lisa.solacelost.dev
    secretName: its-a-lisa-site-cert
  rules:
  - host: its-a-lisa.solacelost.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: its-a-lisa-site
            port:
              number: 3000