kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nodejs-20
  namespace: alyssa
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/fedora/nodejs-20:latest'
      importPolicy:
        scheduled: true
        importMode: Legacy
      referencePolicy:
        type: Local