// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nVTL6BvP7Knk1RSNkBbJCm
// Component: KMO7SWeBEoe7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_core_css from "../core/plasmic.module.css"; // plasmic-import: 3BHMWCYAenCmWb8ThbnzeF/projectcss
import plasmic_semantic_css from "../semantic/plasmic.module.css"; // plasmic-import: dNqcW7FYVqnkjtbdVGjyS8/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: nVTL6BvP7Knk1RSNkBbJCm/projectcss
import sty from "./PlasmicShareIcons.module.css"; // plasmic-import: KMO7SWeBEoe7/css

import FaShareSquaresvgIcon from "./icons/PlasmicIcon__FaShareSquaresvg"; // plasmic-import: H2wqeV9C093q/icon
import FaBookmarkSolidsvgIcon from "./icons/PlasmicIcon__FaBookmarkSolidsvg"; // plasmic-import: NUfRJn8hpkce/icon

createPlasmicElementProxy;

export type PlasmicShareIcons__VariantMembers = {
  removeIcon: "share" | "bookmark" | "email" | "calendar";
};
export type PlasmicShareIcons__VariantsArgs = {
  removeIcon?: MultiChoiceArg<"share" | "bookmark" | "email" | "calendar">;
};
type VariantPropType = keyof PlasmicShareIcons__VariantsArgs;
export const PlasmicShareIcons__VariantProps = new Array<VariantPropType>(
  "removeIcon"
);

export type PlasmicShareIcons__ArgsType = {
  shareSlot?: React.ReactNode;
  bookmarkSlot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicShareIcons__ArgsType;
export const PlasmicShareIcons__ArgProps = new Array<ArgPropType>(
  "shareSlot",
  "bookmarkSlot"
);

export type PlasmicShareIcons__OverridesType = {
  root?: Flex__<"div">;
  socialIconsBase?: Flex__<"div">;
  shareStack?: Flex__<"div">;
  bookmarkStack?: Flex__<"div">;
};

export interface DefaultShareIconsProps {
  shareSlot?: React.ReactNode;
  bookmarkSlot?: React.ReactNode;
  removeIcon?: MultiChoiceArg<"share" | "bookmark" | "email" | "calendar">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicShareIcons__RenderFunc(props: {
  variants: PlasmicShareIcons__VariantsArgs;
  args: PlasmicShareIcons__ArgsType;
  overrides: PlasmicShareIcons__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "removeIcon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.removeIcon
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_core_css.plasmic_tokens,
        plasmic_semantic_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"socialIconsBase"}
        data-plasmic-override={overrides.socialIconsBase}
        className={classNames(projectcss.all, sty.socialIconsBase)}
      >
        <Stack__
          as={"div"}
          data-plasmic-name={"shareStack"}
          data-plasmic-override={overrides.shareStack}
          hasGap={true}
          className={classNames(projectcss.all, sty.shareStack, {
            [sty.shareStackremoveIcon_share]: hasVariant(
              $state,
              "removeIcon",
              "share"
            )
          })}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <FaShareSquaresvgIcon
                className={classNames(projectcss.all, sty.svg___9Guw)}
                role={"img"}
              />
            ),

            value: args.shareSlot
          })}
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"bookmarkStack"}
          data-plasmic-override={overrides.bookmarkStack}
          hasGap={true}
          className={classNames(projectcss.all, sty.bookmarkStack, {
            [sty.bookmarkStackremoveIcon_bookmark]: hasVariant(
              $state,
              "removeIcon",
              "bookmark"
            )
          })}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <FaBookmarkSolidsvgIcon
                className={classNames(projectcss.all, sty.svg__x1DHq)}
                role={"img"}
              />
            ),

            value: args.bookmarkSlot
          })}
        </Stack__>
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "socialIconsBase", "shareStack", "bookmarkStack"],
  socialIconsBase: ["socialIconsBase", "shareStack", "bookmarkStack"],
  shareStack: ["shareStack"],
  bookmarkStack: ["bookmarkStack"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  socialIconsBase: "div";
  shareStack: "div";
  bookmarkStack: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicShareIcons__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicShareIcons__VariantsArgs;
    args?: PlasmicShareIcons__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicShareIcons__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicShareIcons__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicShareIcons__ArgProps,
          internalVariantPropNames: PlasmicShareIcons__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicShareIcons__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShareIcons";
  } else {
    func.displayName = `PlasmicShareIcons.${nodeName}`;
  }
  return func;
}

export const PlasmicShareIcons = Object.assign(
  // Top-level PlasmicShareIcons renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    socialIconsBase: makeNodeComponent("socialIconsBase"),
    shareStack: makeNodeComponent("shareStack"),
    bookmarkStack: makeNodeComponent("bookmarkStack"),

    // Metadata about props expected for PlasmicShareIcons
    internalVariantProps: PlasmicShareIcons__VariantProps,
    internalArgProps: PlasmicShareIcons__ArgProps
  }
);

export default PlasmicShareIcons;
/* prettier-ignore-end */
